# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/huihuihuihuihuihuihuihuihuihui/iOS-Specs.git'

target 'iOSComponentDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iOSComponentDemo
  pod 'iOSComponentModuleA'
  pod 'ModuleACategory'
end
